### ISSUE TITLE
Add option to set output frame rate manually

### ISSUE THREAD

**Issue by BahzBeih** [nihui/cain-ncnn-vulkan#4]
I hope you add the option to set the output frame rate manually like this for example "frame-rate=60"

**Comment by Mar2ck** [comment]
This program doesn't deal with time or speed, it only deal purely in frame count. To add what you're asking nihui would have to add video metadata scanning which is probably out-of-scope for this project. Also Cain isn't capable of generating anything other then 2x frames because it doesn't support time-step.

**Comment by BahzBeih** [comment]
> This program doesn't deal with time or speed, it only deal purely in frame count. To add what you're asking nihui would have to add video metadata scanning which is probably out-of-scope for this project. Also Cain isn't capable of generating anything other then 2x frames because it doesn't support time-step.

thanks a lot for your great help 👍👍👍 so the only solution I can do now is repeating the process several times until I reach the frame rate I want ??? is this right?

**Comment by Mar2ck** [comment]
No prob 👍. Yeah that's pretty much the solution, Cain is built for only 2x interpolation unlike Dain. The process is similar to other AI programs like waifu2x where you have to re-run it until you get it bigger then your target then downscale to exactly what you want after.
